/**
 * Problem DNA: Counting DNA Nucleotides
 * https://rosalind.info/problems/dna/
 * 
 * github.com/evrifaessa
 * yagiz.dev
 */

#include <stdio.h>
#include <string.h>

int main()
{
    char *DNAString = "AGAACTTGAGAGATCATAAGACTTGAACGCGTTCTTCTTTATTGGCTGTTGAAACGACCTCTGCCCCGAGTACGTGACCTCGACAGCGAGTGTTGCAGAGATTTTACAGTCCGTAGTCTTGCCATCCCAATAATGCTTTTCTAGGCTGAATGGGGGTGAAAAGGAGCGCGTAAGTAATACGCCGCCTTGGGGTGGATCTTGCAATGACCCTAGGGATGTATTTCTTGCTGATAAGTTACCAGGACAATTTAACCAGGGAGCACTGTTGAGAATAAAATTGCGATCTGTCTTCAGTCCCGAACGAGAGCAACTGAGGAGGGACGATCGTCCGTAGTACTCCATATTCGTTTGATGTGCAGCCACGTGAGCTGACTGTCAAATTGTCTGAAGGCCGACTGCGGTCCTTCGCACACTGCCGACATGGTTGCGTTCTAGGCGTTCGTCGCTGGGCCTAGCAACTCATGTTCTTTGACGGTTTTAAACCGCGTATTTGTAAAGTGTAACATGACTCGTACAGACGAAACGGAGATACGGATACCCTAACTCAGAGATCCGTGTAATACGACTGCCGCTCTTGTCGCCGATCCGGACTGATTGGAGGATAGATCACATAGCAGTCTCATCACCCACGTCACCTGAAGGATTCTTACACCCAACCCCCGATGGGTCTACCGGGTCGATGGCGCCCCTCCTCGATTTAGCCCTTGGCTGGGCGTGACTCATCCTGCAAATACTACCGGCGACTACGCAACCCACGACTGAGGACAAAATGTAGCACGTCCGTTAAGCTCCATAACTCACGTAGCTATACTAGGCATCGCCTAGAAGTGCGTATTGGTGCGCGCGATAAACAATTTCGGTCTGGATGCTTGTGAGGGA";
    int length = strlen(DNAString);

    int a = 0, c = 0, g = 0, t = 0;

    for (int i = 0; i < length; ++i)
    {
        switch (DNAString[i])
        {
            case 'A': a = a + 1; break;
            case 'C': c = c + 1; break;
            case 'G': g = g + 1; break;
            case 'T': t = t + 1; break;
        }
    }

    printf("The number of nucleotides in \"A C G T\" format: %d %d %d %d\n", a, c, g, t);

    return 0;
}